export type Recommendation = "Strong Buy" | "Buy" | "Hold" | "Avoid";

export type Stock = {
  ticker: string;
  name: string;
  logo: string;
  sector: string;
  industry: string;
  country: string;
  price: number;
  change: number;
  marketCap: string;
  volume: string;
  pe: number;
  eps: number;
  dividend: string;
  high52: number;
  low52: number;
  day: number;
  week: number;
  month: number;
  year: number;
  aiScore: number;
  confidence: number;
  risk: "Low" | "Medium" | "Elevated";
  recommendation: Recommendation;
  revenueGrowth: number;
  earningsGrowth: number;
  margin: number;
  debt: string;
  sentiment: string;
  insider: string;
  valuation: string;
  outlook: string;
  strengths: string[];
  weaknesses: string[];
  chart: number[];
};

export const stocks: Stock[] = [
  {
    ticker: "NVDA",
    name: "Nvidia",
    logo: "NV",
    sector: "Technology",
    industry: "Semiconductors",
    country: "United States",
    price: 132.48,
    change: 3.42,
    marketCap: "$3.26T",
    volume: "214.8M",
    pe: 49.8,
    eps: 2.71,
    dividend: "0.03%",
    high52: 140.76,
    low52: 85.19,
    day: 3.42,
    week: 6.8,
    month: 11.2,
    year: 74.1,
    aiScore: 9.4,
    confidence: 94,
    risk: "Medium",
    recommendation: "Strong Buy",
    revenueGrowth: 79,
    earningsGrowth: 102,
    margin: 57,
    debt: "Low",
    sentiment: "Very bullish",
    insider: "Neutral",
    valuation: "Premium justified by growth",
    outlook: "AI infrastructure demand remains strong across cloud and enterprise buyers.",
    strengths: ["Dominant AI accelerator position", "Exceptional gross margins", "High free cash flow conversion"],
    weaknesses: ["Premium valuation", "Supply-chain concentration", "Cyclical semiconductor exposure"],
    chart: [108, 112, 110, 116, 121, 119, 125, 127, 126, 132]
  },
  {
    ticker: "AAPL",
    name: "Apple",
    logo: "AP",
    sector: "Technology",
    industry: "Consumer Electronics",
    country: "United States",
    price: 214.29,
    change: 1.18,
    marketCap: "$3.18T",
    volume: "61.2M",
    pe: 32.7,
    eps: 6.57,
    dividend: "0.46%",
    high52: 237.49,
    low52: 164.08,
    day: 1.18,
    week: 2.7,
    month: 5.6,
    year: 11.9,
    aiScore: 8.9,
    confidence: 92,
    risk: "Low",
    recommendation: "Strong Buy",
    revenueGrowth: 6,
    earningsGrowth: 10,
    margin: 46,
    debt: "Manageable",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "Fair for quality",
    outlook: "Services growth and device refresh cycles support resilient cash generation.",
    strengths: ["Massive installed base", "High-margin services", "Shareholder returns"],
    weaknesses: ["Hardware replacement cycles", "Regulatory scrutiny", "China demand sensitivity"],
    chart: [186, 191, 188, 193, 199, 202, 198, 207, 211, 214]
  },
  {
    ticker: "MSFT",
    name: "Microsoft",
    logo: "MS",
    sector: "Technology",
    industry: "Software Infrastructure",
    country: "United States",
    price: 468.72,
    change: 0.84,
    marketCap: "$3.48T",
    volume: "28.4M",
    pe: 36.4,
    eps: 12.88,
    dividend: "0.66%",
    high52: 488.92,
    low52: 362.90,
    day: 0.84,
    week: 3.1,
    month: 7.8,
    year: 28.4,
    aiScore: 9.1,
    confidence: 93,
    risk: "Low",
    recommendation: "Strong Buy",
    revenueGrowth: 16,
    earningsGrowth: 20,
    margin: 44,
    debt: "Low",
    sentiment: "Very bullish",
    insider: "Neutral",
    valuation: "Premium quality compounder",
    outlook: "Cloud, AI copilots, and enterprise subscriptions reinforce durable growth.",
    strengths: ["Azure growth", "Recurring enterprise revenue", "Broad AI distribution"],
    weaknesses: ["High expectations", "Cloud capex intensity", "Regulatory complexity"],
    chart: [401, 416, 421, 419, 432, 444, 451, 459, 462, 469]
  },
  {
    ticker: "TSLA",
    name: "Tesla",
    logo: "TS",
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    country: "United States",
    price: 184.06,
    change: -2.72,
    marketCap: "$586.4B",
    volume: "118.9M",
    pe: 48.1,
    eps: 3.83,
    dividend: "0.00%",
    high52: 299.29,
    low52: 138.80,
    day: -2.72,
    week: -4.5,
    month: 8.4,
    year: -24.8,
    aiScore: 6.4,
    confidence: 78,
    risk: "Elevated",
    recommendation: "Hold",
    revenueGrowth: 4,
    earningsGrowth: -18,
    margin: 18,
    debt: "Low",
    sentiment: "Mixed",
    insider: "Light selling",
    valuation: "Future-growth dependent",
    outlook: "Robotaxi and energy optionality compete with margin pressure in autos.",
    strengths: ["Brand and scale", "Energy storage growth", "Balance sheet flexibility"],
    weaknesses: ["Automotive margin compression", "Demand volatility", "Execution risk"],
    chart: [206, 198, 190, 177, 181, 174, 188, 193, 189, 184]
  },
  {
    ticker: "LLY",
    name: "Eli Lilly",
    logo: "LL",
    sector: "Healthcare",
    industry: "Drug Manufacturers",
    country: "United States",
    price: 884.35,
    change: 2.21,
    marketCap: "$839.1B",
    volume: "3.8M",
    pe: 72.5,
    eps: 12.20,
    dividend: "0.59%",
    high52: 966.10,
    low52: 562.12,
    day: 2.21,
    week: 5.1,
    month: 9.7,
    year: 52.4,
    aiScore: 8.7,
    confidence: 90,
    risk: "Medium",
    recommendation: "Buy",
    revenueGrowth: 27,
    earningsGrowth: 35,
    margin: 39,
    debt: "Moderate",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "Premium pipeline valuation",
    outlook: "Obesity and diabetes franchises provide multi-year growth visibility.",
    strengths: ["GLP-1 leadership", "Pricing power", "Pipeline depth"],
    weaknesses: ["Manufacturing constraints", "Patent-cycle exposure", "High valuation"],
    chart: [704, 731, 760, 748, 789, 812, 835, 858, 871, 884]
  },
  {
    ticker: "JPM",
    name: "JPMorgan Chase",
    logo: "JP",
    sector: "Financial Services",
    industry: "Banks",
    country: "United States",
    price: 221.37,
    change: 0.42,
    marketCap: "$621.7B",
    volume: "9.4M",
    pe: 12.4,
    eps: 17.85,
    dividend: "2.08%",
    high52: 230.12,
    low52: 168.44,
    day: 0.42,
    week: 1.6,
    month: 3.2,
    year: 18.9,
    aiScore: 7.8,
    confidence: 86,
    risk: "Low",
    recommendation: "Hold",
    revenueGrowth: 9,
    earningsGrowth: 12,
    margin: 31,
    debt: "Bank leverage",
    sentiment: "Constructive",
    insider: "Neutral",
    valuation: "Attractive versus quality",
    outlook: "Scale advantages and credit discipline support above-peer profitability.",
    strengths: ["Best-in-class balance sheet", "Diversified revenue", "Capital returns"],
    weaknesses: ["Rate sensitivity", "Credit-cycle risk", "Regulatory capital pressure"],
    chart: [188, 193, 197, 202, 199, 207, 214, 218, 216, 221]
  },
  {
    ticker: "XOM",
    name: "Exxon Mobil",
    logo: "XO",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    country: "United States",
    price: 113.64,
    change: -0.68,
    marketCap: "$503.2B",
    volume: "17.1M",
    pe: 13.8,
    eps: 8.23,
    dividend: "3.34%",
    high52: 125.19,
    low52: 95.77,
    day: -0.68,
    week: -1.8,
    month: 2.4,
    year: 6.3,
    aiScore: 6.9,
    confidence: 81,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 3,
    earningsGrowth: -4,
    margin: 13,
    debt: "Low",
    sentiment: "Neutral",
    insider: "Neutral",
    valuation: "Reasonable",
    outlook: "Cash returns remain attractive while commodity prices drive near-term variance.",
    strengths: ["Low-cost assets", "Dividend durability", "Strong balance sheet"],
    weaknesses: ["Commodity cyclicality", "Energy transition risk", "Lower growth profile"],
    chart: [109, 111, 116, 114, 118, 112, 110, 116, 114, 113]
  },
  {
    ticker: "SHOP",
    name: "Shopify",
    logo: "SH",
    sector: "Technology",
    industry: "Software Application",
    country: "Canada",
    price: 67.82,
    change: -4.14,
    marketCap: "$87.5B",
    volume: "15.6M",
    pe: 61.2,
    eps: 1.11,
    dividend: "0.00%",
    high52: 91.57,
    low52: 48.56,
    day: -4.14,
    week: -6.2,
    month: -3.8,
    year: 8.1,
    aiScore: 5.7,
    confidence: 73,
    risk: "Elevated",
    recommendation: "Hold",
    revenueGrowth: 23,
    earningsGrowth: 15,
    margin: 12,
    debt: "Low",
    sentiment: "Mixed",
    insider: "Neutral",
    valuation: "Growth premium",
    outlook: "Merchant growth is solid, but valuation needs sustained margin expansion.",
    strengths: ["Large merchant ecosystem", "Payments attach rate", "International runway"],
    weaknesses: ["Competitive commerce market", "Premium multiple", "Marketing spend intensity"],
    chart: [75, 78, 72, 70, 68, 71, 69, 73, 70, 68]
  },
  {
    ticker: "GOOGL",
    name: "Alphabet",
    logo: "GO",
    sector: "Communication Services",
    industry: "Internet Content & Information",
    country: "United States",
    price: 176.41,
    change: 1.34,
    marketCap: "$2.18T",
    volume: "31.7M",
    pe: 24.9,
    eps: 7.08,
    dividend: "0.45%",
    high52: 191.75,
    low52: 127.90,
    day: 1.34,
    week: 2.9,
    month: 6.4,
    year: 24.7,
    aiScore: 8.6,
    confidence: 91,
    risk: "Low",
    recommendation: "Buy",
    revenueGrowth: 14,
    earningsGrowth: 28,
    margin: 30,
    debt: "Very low",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "Attractive for AI and ads scale",
    outlook: "Search, YouTube, cloud, and AI infrastructure keep growth durable.",
    strengths: ["Search cash flow", "YouTube reach", "Strong balance sheet"],
    weaknesses: ["AI search disruption risk", "Regulatory pressure", "Cloud competition"],
    chart: [142, 148, 151, 156, 162, 158, 166, 171, 173, 176]
  },
  {
    ticker: "AMZN",
    name: "Amazon",
    logo: "AM",
    sector: "Consumer Cyclical",
    industry: "Internet Retail",
    country: "United States",
    price: 187.23,
    change: 2.08,
    marketCap: "$1.96T",
    volume: "43.6M",
    pe: 41.3,
    eps: 4.53,
    dividend: "0.00%",
    high52: 201.20,
    low52: 118.35,
    day: 2.08,
    week: 4.2,
    month: 8.1,
    year: 37.6,
    aiScore: 8.8,
    confidence: 90,
    risk: "Medium",
    recommendation: "Strong Buy",
    revenueGrowth: 13,
    earningsGrowth: 55,
    margin: 10,
    debt: "Manageable",
    sentiment: "Very bullish",
    insider: "Neutral",
    valuation: "Fair if AWS margins expand",
    outlook: "AWS, ads, and retail efficiency are lifting earnings faster than revenue.",
    strengths: ["AWS scale", "Advertising growth", "Retail logistics moat"],
    weaknesses: ["Thin retail margins", "Cloud capex", "Regulatory scrutiny"],
    chart: [139, 144, 151, 149, 158, 166, 171, 178, 183, 187]
  },
  {
    ticker: "META",
    name: "Meta Platforms",
    logo: "ME",
    sector: "Communication Services",
    industry: "Internet Content & Information",
    country: "United States",
    price: 512.70,
    change: 1.92,
    marketCap: "$1.30T",
    volume: "14.2M",
    pe: 27.4,
    eps: 18.71,
    dividend: "0.39%",
    high52: 542.81,
    low52: 274.38,
    day: 1.92,
    week: 3.9,
    month: 7.5,
    year: 67.2,
    aiScore: 8.5,
    confidence: 89,
    risk: "Medium",
    recommendation: "Buy",
    revenueGrowth: 22,
    earningsGrowth: 73,
    margin: 35,
    debt: "Low",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "Reasonable versus growth",
    outlook: "Ad targeting recovery and AI engagement tools support stronger margins.",
    strengths: ["Massive social graph", "AI ad tools", "High cash generation"],
    weaknesses: ["Reality Labs losses", "Policy risk", "Ad-cycle sensitivity"],
    chart: [333, 356, 382, 408, 431, 454, 477, 493, 506, 513]
  },
  {
    ticker: "AVGO",
    name: "Broadcom",
    logo: "AV",
    sector: "Technology",
    industry: "Semiconductors",
    country: "United States",
    price: 168.35,
    change: 3.76,
    marketCap: "$783.6B",
    volume: "28.5M",
    pe: 36.8,
    eps: 4.57,
    dividend: "1.25%",
    high52: 185.16,
    low52: 79.51,
    day: 3.76,
    week: 6.1,
    month: 12.8,
    year: 89.4,
    aiScore: 8.9,
    confidence: 91,
    risk: "Medium",
    recommendation: "Strong Buy",
    revenueGrowth: 34,
    earningsGrowth: 25,
    margin: 41,
    debt: "Moderate",
    sentiment: "Very bullish",
    insider: "Neutral",
    valuation: "Premium AI infrastructure name",
    outlook: "Custom AI silicon and infrastructure software create a strong compounder profile.",
    strengths: ["AI networking demand", "VMware cash flow", "Dividend growth"],
    weaknesses: ["Integration debt", "Customer concentration", "Semiconductor cycles"],
    chart: [94, 103, 111, 119, 128, 136, 149, 158, 162, 168]
  },
  {
    ticker: "AMD",
    name: "Advanced Micro Devices",
    logo: "AM",
    sector: "Technology",
    industry: "Semiconductors",
    country: "United States",
    price: 156.90,
    change: 4.58,
    marketCap: "$253.6B",
    volume: "63.9M",
    pe: 58.5,
    eps: 2.68,
    dividend: "0.00%",
    high52: 227.30,
    low52: 93.12,
    day: 4.58,
    week: 7.3,
    month: 14.5,
    year: 21.8,
    aiScore: 7.9,
    confidence: 84,
    risk: "Elevated",
    recommendation: "Hold",
    revenueGrowth: 18,
    earningsGrowth: 22,
    margin: 22,
    debt: "Low",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "AI share gains priced in",
    outlook: "AI GPU traction could unlock upside if margins and supply improve.",
    strengths: ["Data-center runway", "CPU share gains", "Strong engineering"],
    weaknesses: ["AI execution gap", "Premium valuation", "PC cycle exposure"],
    chart: [119, 126, 131, 124, 136, 142, 148, 151, 153, 157]
  },
  {
    ticker: "ORCL",
    name: "Oracle",
    logo: "OR",
    sector: "Technology",
    industry: "Software Infrastructure",
    country: "United States",
    price: 137.18,
    change: 2.44,
    marketCap: "$378.7B",
    volume: "10.8M",
    pe: 31.6,
    eps: 4.34,
    dividend: "1.17%",
    high52: 146.59,
    low52: 99.26,
    day: 2.44,
    week: 4.4,
    month: 9.9,
    year: 14.6,
    aiScore: 7.7,
    confidence: 84,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 10,
    earningsGrowth: 12,
    margin: 29,
    debt: "Moderate",
    sentiment: "Constructive",
    insider: "Neutral",
    valuation: "Fair for cloud backlog",
    outlook: "Cloud infrastructure demand and database stickiness support steady growth.",
    strengths: ["Database moat", "Cloud backlog", "Enterprise renewals"],
    weaknesses: ["Debt load", "Cloud competition", "Slower organic growth"],
    chart: [107, 112, 118, 116, 123, 126, 130, 134, 132, 137]
  },
  {
    ticker: "CRM",
    name: "Salesforce",
    logo: "CR",
    sector: "Technology",
    industry: "Software Application",
    country: "United States",
    price: 248.62,
    change: -1.15,
    marketCap: "$239.8B",
    volume: "7.1M",
    pe: 28.2,
    eps: 8.82,
    dividend: "0.64%",
    high52: 318.71,
    low52: 193.68,
    day: -1.15,
    week: -2.1,
    month: 1.8,
    year: 17.5,
    aiScore: 7.2,
    confidence: 82,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 11,
    earningsGrowth: 21,
    margin: 19,
    debt: "Low",
    sentiment: "Mixed",
    insider: "Neutral",
    valuation: "Reasonable after pullback",
    outlook: "AI features may improve seat expansion, but enterprise budgets remain selective.",
    strengths: ["CRM leadership", "Margin expansion", "Large installed base"],
    weaknesses: ["Growth slowdown", "Seat saturation", "Competitive AI software"],
    chart: [214, 226, 238, 249, 241, 258, 266, 253, 251, 249]
  },
  {
    ticker: "NFLX",
    name: "Netflix",
    logo: "NF",
    sector: "Communication Services",
    industry: "Entertainment",
    country: "United States",
    price: 648.55,
    change: 1.63,
    marketCap: "$279.4B",
    volume: "3.6M",
    pe: 37.1,
    eps: 17.48,
    dividend: "0.00%",
    high52: 697.49,
    low52: 344.73,
    day: 1.63,
    week: 3.3,
    month: 6.7,
    year: 48.2,
    aiScore: 7.9,
    confidence: 85,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 15,
    earningsGrowth: 42,
    margin: 24,
    debt: "Manageable",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "Content leader premium",
    outlook: "Ad tier and paid sharing improve monetization across a global subscriber base.",
    strengths: ["Streaming scale", "Pricing power", "Content engine"],
    weaknesses: ["Content spending", "Competition", "Subscriber maturity"],
    chart: [432, 468, 501, 533, 558, 587, 604, 626, 639, 649]
  },
  {
    ticker: "COST",
    name: "Costco Wholesale",
    logo: "CO",
    sector: "Consumer Defensive",
    industry: "Discount Stores",
    country: "United States",
    price: 848.31,
    change: 0.88,
    marketCap: "$376.2B",
    volume: "1.9M",
    pe: 52.6,
    eps: 16.13,
    dividend: "0.55%",
    high52: 873.96,
    low52: 524.63,
    day: 0.88,
    week: 2.6,
    month: 5.9,
    year: 44.8,
    aiScore: 8.1,
    confidence: 88,
    risk: "Low",
    recommendation: "Buy",
    revenueGrowth: 7,
    earningsGrowth: 13,
    margin: 3,
    debt: "Low",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "Premium defensive compounder",
    outlook: "Membership loyalty and traffic growth keep Costco in elite quality screens.",
    strengths: ["Membership model", "Traffic consistency", "Balance sheet strength"],
    weaknesses: ["Very high multiple", "Thin margins", "Limited margin upside"],
    chart: [601, 634, 662, 690, 718, 746, 781, 806, 831, 848]
  },
  {
    ticker: "WMT",
    name: "Walmart",
    logo: "WM",
    sector: "Consumer Defensive",
    industry: "Discount Stores",
    country: "United States",
    price: 68.14,
    change: 0.62,
    marketCap: "$548.5B",
    volume: "16.4M",
    pe: 29.5,
    eps: 2.31,
    dividend: "1.21%",
    high52: 70.45,
    low52: 49.85,
    day: 0.62,
    week: 1.7,
    month: 4.2,
    year: 29.9,
    aiScore: 7.8,
    confidence: 86,
    risk: "Low",
    recommendation: "Hold",
    revenueGrowth: 5,
    earningsGrowth: 8,
    margin: 4,
    debt: "Manageable",
    sentiment: "Constructive",
    insider: "Neutral",
    valuation: "Fair defensive premium",
    outlook: "Grocery share, advertising, and e-commerce add stability to defensive growth.",
    strengths: ["Scale advantage", "Grocery leadership", "Ad business growth"],
    weaknesses: ["Labor costs", "Low margins", "Valuation premium"],
    chart: [52, 54, 56, 58, 61, 63, 64, 66, 67, 68]
  },
  {
    ticker: "HD",
    name: "Home Depot",
    logo: "HD",
    sector: "Consumer Cyclical",
    industry: "Home Improvement Retail",
    country: "United States",
    price: 356.77,
    change: -0.74,
    marketCap: "$354.1B",
    volume: "3.4M",
    pe: 23.8,
    eps: 14.99,
    dividend: "2.53%",
    high52: 396.87,
    low52: 274.26,
    day: -0.74,
    week: 0.9,
    month: 3.1,
    year: 15.4,
    aiScore: 7.1,
    confidence: 82,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 3,
    earningsGrowth: 4,
    margin: 10,
    debt: "Moderate",
    sentiment: "Neutral",
    insider: "Neutral",
    valuation: "Fair for housing recovery",
    outlook: "Housing turnover recovery could reaccelerate big-ticket demand.",
    strengths: ["Brand moat", "Pro customer base", "Dividend growth"],
    weaknesses: ["Housing cycle", "Big-ticket weakness", "Debt-funded buybacks"],
    chart: [301, 318, 329, 322, 337, 346, 352, 361, 359, 357]
  },
  {
    ticker: "MCD",
    name: "McDonald's",
    logo: "MC",
    sector: "Consumer Cyclical",
    industry: "Restaurants",
    country: "United States",
    price: 263.42,
    change: -0.35,
    marketCap: "$189.6B",
    volume: "3.1M",
    pe: 22.4,
    eps: 11.76,
    dividend: "2.52%",
    high52: 302.39,
    low52: 243.53,
    day: -0.35,
    week: -1.4,
    month: 1.2,
    year: -7.9,
    aiScore: 6.8,
    confidence: 80,
    risk: "Low",
    recommendation: "Hold",
    revenueGrowth: 4,
    earningsGrowth: 6,
    margin: 32,
    debt: "Moderate",
    sentiment: "Neutral",
    insider: "Neutral",
    valuation: "Reasonable defensive brand",
    outlook: "Global franchising remains strong, but value pressure weighs on traffic.",
    strengths: ["Global brand", "Franchise margins", "Dividend record"],
    weaknesses: ["Consumer price sensitivity", "FX headwinds", "Slower traffic"],
    chart: [288, 282, 276, 269, 261, 255, 260, 266, 264, 263]
  },
  {
    ticker: "V",
    name: "Visa",
    logo: "VI",
    sector: "Financial Services",
    industry: "Credit Services",
    country: "United States",
    price: 275.11,
    change: 0.94,
    marketCap: "$548.7B",
    volume: "7.2M",
    pe: 30.1,
    eps: 9.14,
    dividend: "0.75%",
    high52: 290.96,
    low52: 227.78,
    day: 0.94,
    week: 2.2,
    month: 4.1,
    year: 19.6,
    aiScore: 8.2,
    confidence: 89,
    risk: "Low",
    recommendation: "Buy",
    revenueGrowth: 10,
    earningsGrowth: 15,
    margin: 54,
    debt: "Low",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "Quality premium",
    outlook: "Global payments growth and cross-border volume support durable compounding.",
    strengths: ["Network moat", "High margins", "Global scale"],
    weaknesses: ["Regulatory fees", "Consumer spending cycles", "Fintech competition"],
    chart: [235, 242, 251, 256, 263, 259, 267, 272, 274, 275]
  },
  {
    ticker: "MA",
    name: "Mastercard",
    logo: "MA",
    sector: "Financial Services",
    industry: "Credit Services",
    country: "United States",
    price: 456.89,
    change: 1.08,
    marketCap: "$421.8B",
    volume: "2.6M",
    pe: 34.2,
    eps: 13.36,
    dividend: "0.58%",
    high52: 490.00,
    low52: 359.77,
    day: 1.08,
    week: 2.7,
    month: 4.9,
    year: 18.8,
    aiScore: 8.1,
    confidence: 88,
    risk: "Low",
    recommendation: "Buy",
    revenueGrowth: 11,
    earningsGrowth: 16,
    margin: 46,
    debt: "Low",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "Premium network asset",
    outlook: "Consumer payments and value-added services support steady earnings growth.",
    strengths: ["Payments moat", "International exposure", "Strong margins"],
    weaknesses: ["Regulatory pressure", "Macro sensitivity", "Premium valuation"],
    chart: [382, 397, 411, 425, 437, 432, 444, 452, 455, 457]
  },
  {
    ticker: "BAC",
    name: "Bank of America",
    logo: "BA",
    sector: "Financial Services",
    industry: "Banks",
    country: "United States",
    price: 39.25,
    change: 1.22,
    marketCap: "$303.4B",
    volume: "42.8M",
    pe: 13.7,
    eps: 2.86,
    dividend: "2.45%",
    high52: 41.92,
    low52: 24.96,
    day: 1.22,
    week: 3.2,
    month: 6.2,
    year: 34.5,
    aiScore: 6.6,
    confidence: 78,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 2,
    earningsGrowth: -3,
    margin: 25,
    debt: "Bank leverage",
    sentiment: "Neutral",
    insider: "Neutral",
    valuation: "Discount to quality banks",
    outlook: "Improving rate visibility helps, but deposit costs still pressure earnings.",
    strengths: ["Large deposit base", "Consumer banking scale", "Dividend yield"],
    weaknesses: ["Rate sensitivity", "Unrealized securities losses", "Credit-cycle risk"],
    chart: [27, 29, 31, 33, 35, 34, 36, 38, 39, 39]
  },
  {
    ticker: "BRK.B",
    name: "Berkshire Hathaway",
    logo: "BR",
    sector: "Financial Services",
    industry: "Insurance Diversified",
    country: "United States",
    price: 412.52,
    change: 0.51,
    marketCap: "$889.7B",
    volume: "3.9M",
    pe: 11.3,
    eps: 36.51,
    dividend: "0.00%",
    high52: 430.00,
    low52: 330.58,
    day: 0.51,
    week: 1.1,
    month: 2.6,
    year: 21.7,
    aiScore: 7.6,
    confidence: 87,
    risk: "Low",
    recommendation: "Hold",
    revenueGrowth: 8,
    earningsGrowth: 14,
    margin: 18,
    debt: "Very low",
    sentiment: "Constructive",
    insider: "Neutral",
    valuation: "Defensive value compounder",
    outlook: "Insurance float, cash reserves, and operating businesses provide resilience.",
    strengths: ["Fortress balance sheet", "Diversified earnings", "Insurance float"],
    weaknesses: ["Succession concerns", "Huge cash drag", "Limited dividend appeal"],
    chart: [345, 356, 368, 377, 386, 394, 401, 407, 410, 413]
  },
  {
    ticker: "UNH",
    name: "UnitedHealth Group",
    logo: "UN",
    sector: "Healthcare",
    industry: "Healthcare Plans",
    country: "United States",
    price: 498.75,
    change: -1.88,
    marketCap: "$458.9B",
    volume: "4.7M",
    pe: 20.9,
    eps: 23.86,
    dividend: "1.67%",
    high52: 554.70,
    low52: 436.38,
    day: -1.88,
    week: -3.6,
    month: -1.9,
    year: 3.4,
    aiScore: 7.0,
    confidence: 80,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 9,
    earningsGrowth: 8,
    margin: 6,
    debt: "Manageable",
    sentiment: "Mixed",
    insider: "Neutral",
    valuation: "Fair after uncertainty",
    outlook: "Scale remains strong, though utilization and policy headlines weigh on sentiment.",
    strengths: ["Healthcare scale", "Optum growth", "Cash flow stability"],
    weaknesses: ["Policy risk", "Medical cost pressure", "Margin scrutiny"],
    chart: [481, 493, 512, 529, 518, 506, 492, 501, 507, 499]
  },
  {
    ticker: "JNJ",
    name: "Johnson & Johnson",
    logo: "JN",
    sector: "Healthcare",
    industry: "Drug Manufacturers",
    country: "United States",
    price: 146.92,
    change: 0.28,
    marketCap: "$353.6B",
    volume: "7.8M",
    pe: 15.8,
    eps: 9.30,
    dividend: "3.38%",
    high52: 175.97,
    low52: 143.13,
    day: 0.28,
    week: 0.6,
    month: -1.2,
    year: -9.6,
    aiScore: 6.7,
    confidence: 81,
    risk: "Low",
    recommendation: "Hold",
    revenueGrowth: 4,
    earningsGrowth: 5,
    margin: 22,
    debt: "Low",
    sentiment: "Neutral",
    insider: "Neutral",
    valuation: "Defensive dividend value",
    outlook: "Pharma pipeline and medtech provide stability, but litigation clouds remain.",
    strengths: ["Dividend durability", "Healthcare diversification", "Strong credit profile"],
    weaknesses: ["Legal overhang", "Slow growth", "Pipeline execution"],
    chart: [160, 157, 153, 149, 146, 148, 151, 149, 147, 147]
  },
  {
    ticker: "MRK",
    name: "Merck",
    logo: "MR",
    sector: "Healthcare",
    industry: "Drug Manufacturers",
    country: "United States",
    price: 128.44,
    change: 0.79,
    marketCap: "$325.4B",
    volume: "8.6M",
    pe: 18.7,
    eps: 6.87,
    dividend: "2.34%",
    high52: 133.10,
    low52: 99.14,
    day: 0.79,
    week: 2.1,
    month: 4.7,
    year: 19.1,
    aiScore: 7.4,
    confidence: 84,
    risk: "Low",
    recommendation: "Hold",
    revenueGrowth: 7,
    earningsGrowth: 9,
    margin: 28,
    debt: "Manageable",
    sentiment: "Constructive",
    insider: "Neutral",
    valuation: "Fair with patent risk",
    outlook: "Keytruda strength continues, while patent cliffs keep the market selective.",
    strengths: ["Oncology leadership", "Dividend profile", "Pipeline investment"],
    weaknesses: ["Patent concentration", "Trial risk", "Slower non-oncology growth"],
    chart: [104, 109, 112, 115, 119, 121, 124, 126, 127, 128]
  },
  {
    ticker: "PFE",
    name: "Pfizer",
    logo: "PF",
    sector: "Healthcare",
    industry: "Drug Manufacturers",
    country: "United States",
    price: 29.66,
    change: -0.92,
    marketCap: "$168.1B",
    volume: "33.2M",
    pe: 12.6,
    eps: 2.35,
    dividend: "5.67%",
    high52: 39.87,
    low52: 25.20,
    day: -0.92,
    week: -1.8,
    month: 2.9,
    year: -18.4,
    aiScore: 5.8,
    confidence: 74,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: -19,
    earningsGrowth: -28,
    margin: 18,
    debt: "Moderate",
    sentiment: "Mixed",
    insider: "Neutral",
    valuation: "Cheap but turnaround-dependent",
    outlook: "Dividend yield is attractive, but post-COVID reset needs clearer pipeline wins.",
    strengths: ["High dividend", "Large pipeline", "Global pharma scale"],
    weaknesses: ["Revenue decline", "Debt after acquisitions", "Patent risk"],
    chart: [36, 34, 32, 29, 27, 26, 28, 30, 31, 30]
  },
  {
    ticker: "ABBV",
    name: "AbbVie",
    logo: "AB",
    sector: "Healthcare",
    industry: "Drug Manufacturers",
    country: "United States",
    price: 171.80,
    change: 0.44,
    marketCap: "$303.7B",
    volume: "5.2M",
    pe: 16.5,
    eps: 10.41,
    dividend: "3.62%",
    high52: 182.89,
    low52: 130.96,
    day: 0.44,
    week: 1.9,
    month: 3.8,
    year: 26.3,
    aiScore: 7.5,
    confidence: 84,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 5,
    earningsGrowth: 7,
    margin: 26,
    debt: "Moderate",
    sentiment: "Constructive",
    insider: "Neutral",
    valuation: "Fair dividend growth",
    outlook: "Immunology transition is improving as newer drugs offset Humira erosion.",
    strengths: ["Dividend growth", "Immunology franchise", "Cash generation"],
    weaknesses: ["Patent cliffs", "Acquisition debt", "Pipeline concentration"],
    chart: [139, 146, 151, 158, 163, 166, 169, 173, 170, 172]
  },
  {
    ticker: "KO",
    name: "Coca-Cola",
    logo: "KO",
    sector: "Consumer Defensive",
    industry: "Beverages Non-Alcoholic",
    country: "United States",
    price: 62.85,
    change: 0.16,
    marketCap: "$270.8B",
    volume: "12.1M",
    pe: 24.8,
    eps: 2.53,
    dividend: "3.08%",
    high52: 64.36,
    low52: 51.55,
    day: 0.16,
    week: 0.8,
    month: 2.4,
    year: 5.6,
    aiScore: 7.2,
    confidence: 83,
    risk: "Low",
    recommendation: "Hold",
    revenueGrowth: 6,
    earningsGrowth: 7,
    margin: 23,
    debt: "Manageable",
    sentiment: "Neutral",
    insider: "Neutral",
    valuation: "Defensive income premium",
    outlook: "Global brand power and pricing support steady dividend-style returns.",
    strengths: ["Global distribution", "Pricing power", "Dividend consistency"],
    weaknesses: ["Slower growth", "FX sensitivity", "Health trend pressure"],
    chart: [59, 60, 61, 60, 62, 63, 62, 63, 62, 63]
  },
  {
    ticker: "PEP",
    name: "PepsiCo",
    logo: "PE",
    sector: "Consumer Defensive",
    industry: "Beverages Non-Alcoholic",
    country: "United States",
    price: 171.36,
    change: 0.12,
    marketCap: "$235.4B",
    volume: "4.9M",
    pe: 22.9,
    eps: 7.48,
    dividend: "3.15%",
    high52: 196.88,
    low52: 155.83,
    day: 0.12,
    week: 1.1,
    month: 2.6,
    year: -5.7,
    aiScore: 7.0,
    confidence: 82,
    risk: "Low",
    recommendation: "Hold",
    revenueGrowth: 5,
    earningsGrowth: 7,
    margin: 11,
    debt: "Manageable",
    sentiment: "Neutral",
    insider: "Neutral",
    valuation: "Fair defensive income",
    outlook: "Snacks and beverages create stability, though volume growth is modest.",
    strengths: ["Snack portfolio", "Dividend growth", "Global brands"],
    weaknesses: ["Volume softness", "FX pressure", "Input-cost sensitivity"],
    chart: [184, 179, 174, 168, 162, 160, 165, 169, 170, 171]
  },
  {
    ticker: "PG",
    name: "Procter & Gamble",
    logo: "PG",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    country: "United States",
    price: 164.22,
    change: 0.31,
    marketCap: "$386.9B",
    volume: "6.1M",
    pe: 26.4,
    eps: 6.22,
    dividend: "2.43%",
    high52: 169.41,
    low52: 141.45,
    day: 0.31,
    week: 1.3,
    month: 3.1,
    year: 10.4,
    aiScore: 7.3,
    confidence: 84,
    risk: "Low",
    recommendation: "Hold",
    revenueGrowth: 4,
    earningsGrowth: 8,
    margin: 19,
    debt: "Low",
    sentiment: "Constructive",
    insider: "Neutral",
    valuation: "Premium staple compounder",
    outlook: "Brand strength and productivity savings keep earnings steady.",
    strengths: ["Category-leading brands", "Dividend record", "Pricing discipline"],
    weaknesses: ["Slow volume growth", "Commodity costs", "Premium valuation"],
    chart: [146, 149, 151, 154, 158, 160, 162, 163, 165, 164]
  },
  {
    ticker: "CVX",
    name: "Chevron",
    logo: "CV",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    country: "United States",
    price: 156.48,
    change: -0.41,
    marketCap: "$288.9B",
    volume: "8.4M",
    pe: 14.7,
    eps: 10.65,
    dividend: "4.10%",
    high52: 171.70,
    low52: 139.62,
    day: -0.41,
    week: -0.9,
    month: 1.6,
    year: 0.8,
    aiScore: 6.7,
    confidence: 80,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 2,
    earningsGrowth: -5,
    margin: 12,
    debt: "Low",
    sentiment: "Neutral",
    insider: "Neutral",
    valuation: "Dividend value",
    outlook: "Shareholder returns stay solid, but commodity prices dominate returns.",
    strengths: ["Dividend yield", "Permian exposure", "Strong balance sheet"],
    weaknesses: ["Oil price sensitivity", "Acquisition execution", "Energy transition risk"],
    chart: [151, 154, 159, 162, 158, 153, 150, 155, 158, 156]
  },
  {
    ticker: "CAT",
    name: "Caterpillar",
    logo: "CA",
    sector: "Industrials",
    industry: "Farm & Heavy Construction Machinery",
    country: "United States",
    price: 333.12,
    change: 1.54,
    marketCap: "$161.8B",
    volume: "2.8M",
    pe: 15.0,
    eps: 22.21,
    dividend: "1.66%",
    high52: 382.01,
    low52: 223.76,
    day: 1.54,
    week: 2.6,
    month: 5.1,
    year: 35.4,
    aiScore: 7.4,
    confidence: 83,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 8,
    earningsGrowth: 18,
    margin: 16,
    debt: "Manageable",
    sentiment: "Constructive",
    insider: "Neutral",
    valuation: "Reasonable cyclical quality",
    outlook: "Infrastructure, energy, and mining demand keep order books healthy.",
    strengths: ["Dealer network", "Pricing power", "Infrastructure exposure"],
    weaknesses: ["Cyclical demand", "China weakness", "Inventory risk"],
    chart: [246, 268, 285, 301, 318, 326, 341, 352, 338, 333]
  },
  {
    ticker: "GE",
    name: "GE Aerospace",
    logo: "GE",
    sector: "Industrials",
    industry: "Aerospace & Defense",
    country: "United States",
    price: 162.77,
    change: 2.02,
    marketCap: "$177.4B",
    volume: "6.7M",
    pe: 33.1,
    eps: 4.92,
    dividend: "0.68%",
    high52: 170.80,
    low52: 82.11,
    day: 2.02,
    week: 4.7,
    month: 9.5,
    year: 86.8,
    aiScore: 8.0,
    confidence: 86,
    risk: "Medium",
    recommendation: "Buy",
    revenueGrowth: 17,
    earningsGrowth: 32,
    margin: 20,
    debt: "Low",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "Premium aerospace recovery",
    outlook: "Commercial engine services and defense demand create strong earnings visibility.",
    strengths: ["Engine service moat", "Aerospace backlog", "Margin expansion"],
    weaknesses: ["Supply chain strain", "Aviation cycle", "Premium valuation"],
    chart: [88, 101, 114, 126, 138, 146, 153, 159, 161, 163]
  },
  {
    ticker: "BA",
    name: "Boeing",
    logo: "BO",
    sector: "Industrials",
    industry: "Aerospace & Defense",
    country: "United States",
    price: 181.22,
    change: -1.73,
    marketCap: "$111.2B",
    volume: "9.5M",
    pe: 0,
    eps: -3.12,
    dividend: "0.00%",
    high52: 267.54,
    low52: 159.70,
    day: -1.73,
    week: -2.8,
    month: 4.5,
    year: -14.9,
    aiScore: 4.9,
    confidence: 70,
    risk: "Elevated",
    recommendation: "Avoid",
    revenueGrowth: 6,
    earningsGrowth: -22,
    margin: -2,
    debt: "High",
    sentiment: "Bearish",
    insider: "Neutral",
    valuation: "Turnaround speculative",
    outlook: "Backlog is valuable, but quality, cash flow, and regulatory issues remain heavy.",
    strengths: ["Aircraft backlog", "Duopoly position", "Defense exposure"],
    weaknesses: ["Execution risk", "High debt", "Negative cash flow"],
    chart: [249, 235, 218, 196, 177, 162, 171, 186, 184, 181]
  },
  {
    ticker: "DIS",
    name: "Walt Disney",
    logo: "DI",
    sector: "Communication Services",
    industry: "Entertainment",
    country: "United States",
    price: 101.84,
    change: 0.57,
    marketCap: "$185.9B",
    volume: "10.3M",
    pe: 28.7,
    eps: 3.55,
    dividend: "0.89%",
    high52: 123.74,
    low52: 78.73,
    day: 0.57,
    week: 1.9,
    month: 3.5,
    year: 12.4,
    aiScore: 6.5,
    confidence: 78,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 4,
    earningsGrowth: 15,
    margin: 8,
    debt: "Manageable",
    sentiment: "Mixed",
    insider: "Neutral",
    valuation: "Turnaround value",
    outlook: "Parks remain strong while streaming profitability and media assets reset.",
    strengths: ["Iconic IP", "Parks cash flow", "Streaming scale"],
    weaknesses: ["Linear TV decline", "Content costs", "Turnaround complexity"],
    chart: [83, 89, 95, 101, 112, 119, 111, 104, 100, 102]
  },
  {
    ticker: "NKE",
    name: "Nike",
    logo: "NI",
    sector: "Consumer Cyclical",
    industry: "Footwear & Accessories",
    country: "United States",
    price: 94.31,
    change: -2.15,
    marketCap: "$142.4B",
    volume: "12.9M",
    pe: 25.3,
    eps: 3.73,
    dividend: "1.56%",
    high52: 123.39,
    low52: 88.66,
    day: -2.15,
    week: -4.2,
    month: -1.8,
    year: -14.3,
    aiScore: 5.9,
    confidence: 74,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 2,
    earningsGrowth: 5,
    margin: 11,
    debt: "Low",
    sentiment: "Mixed",
    insider: "Neutral",
    valuation: "Brand turnaround",
    outlook: "Brand strength remains, but innovation and wholesale mix need a reset.",
    strengths: ["Global brand", "Direct channel", "Margin potential"],
    weaknesses: ["Demand softness", "Competition", "Inventory resets"],
    chart: [116, 111, 105, 98, 92, 89, 93, 97, 96, 94]
  },
  {
    ticker: "SBUX",
    name: "Starbucks",
    logo: "SB",
    sector: "Consumer Cyclical",
    industry: "Restaurants",
    country: "United States",
    price: 78.45,
    change: -0.86,
    marketCap: "$88.9B",
    volume: "11.6M",
    pe: 21.5,
    eps: 3.65,
    dividend: "2.89%",
    high52: 107.66,
    low52: 71.80,
    day: -0.86,
    week: -1.9,
    month: 0.6,
    year: -22.7,
    aiScore: 5.6,
    confidence: 73,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 3,
    earningsGrowth: 4,
    margin: 11,
    debt: "Moderate",
    sentiment: "Mixed",
    insider: "Neutral",
    valuation: "Turnaround dependent",
    outlook: "Traffic recovery and China demand are needed before the story improves.",
    strengths: ["Brand loyalty", "Rewards ecosystem", "Global footprint"],
    weaknesses: ["Traffic weakness", "China competition", "Labor pressure"],
    chart: [98, 94, 89, 84, 79, 73, 76, 81, 80, 78]
  },
  {
    ticker: "T",
    name: "AT&T",
    logo: "AT",
    sector: "Communication Services",
    industry: "Telecom Services",
    country: "United States",
    price: 18.22,
    change: 0.39,
    marketCap: "$130.6B",
    volume: "37.5M",
    pe: 9.1,
    eps: 2.00,
    dividend: "6.11%",
    high52: 18.45,
    low52: 13.43,
    day: 0.39,
    week: 1.6,
    month: 4.2,
    year: 18.6,
    aiScore: 6.1,
    confidence: 77,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 1,
    earningsGrowth: 3,
    margin: 13,
    debt: "High",
    sentiment: "Neutral",
    insider: "Neutral",
    valuation: "Income value",
    outlook: "Wireless stability and debt paydown support income investors.",
    strengths: ["High yield", "Wireless scale", "Fiber growth"],
    weaknesses: ["High debt", "Slow growth", "Capital intensity"],
    chart: [14, 15, 16, 16, 17, 17, 18, 18, 18, 18]
  },
  {
    ticker: "VZ",
    name: "Verizon",
    logo: "VZ",
    sector: "Communication Services",
    industry: "Telecom Services",
    country: "United States",
    price: 40.18,
    change: 0.21,
    marketCap: "$169.2B",
    volume: "19.1M",
    pe: 9.4,
    eps: 4.27,
    dividend: "6.62%",
    high52: 43.42,
    low52: 30.14,
    day: 0.21,
    week: 0.7,
    month: 2.1,
    year: 10.9,
    aiScore: 6.3,
    confidence: 78,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 1,
    earningsGrowth: 2,
    margin: 14,
    debt: "High",
    sentiment: "Neutral",
    insider: "Neutral",
    valuation: "Income value",
    outlook: "Stable cash flows and yield appeal, but growth remains modest.",
    strengths: ["Dividend yield", "Network quality", "Predictable cash flow"],
    weaknesses: ["High leverage", "Slow revenue growth", "Capex needs"],
    chart: [33, 35, 37, 38, 39, 41, 40, 42, 41, 40]
  },
  {
    ticker: "PLTR",
    name: "Palantir",
    logo: "PL",
    sector: "Technology",
    industry: "Software Infrastructure",
    country: "United States",
    price: 26.72,
    change: 5.14,
    marketCap: "$59.4B",
    volume: "64.8M",
    pe: 79.8,
    eps: 0.34,
    dividend: "0.00%",
    high52: 29.83,
    low52: 13.68,
    day: 5.14,
    week: 9.2,
    month: 18.7,
    year: 72.5,
    aiScore: 7.3,
    confidence: 80,
    risk: "Elevated",
    recommendation: "Hold",
    revenueGrowth: 21,
    earningsGrowth: 38,
    margin: 16,
    debt: "Very low",
    sentiment: "Bullish",
    insider: "Light selling",
    valuation: "High-growth premium",
    outlook: "AI platform adoption is strong, but valuation demands flawless execution.",
    strengths: ["AI platform momentum", "Government contracts", "Debt-free balance sheet"],
    weaknesses: ["High multiple", "Customer concentration", "Stock volatility"],
    chart: [15, 17, 18, 19, 21, 20, 23, 25, 26, 27]
  },
  {
    ticker: "SNOW",
    name: "Snowflake",
    logo: "SN",
    sector: "Technology",
    industry: "Software Application",
    country: "United States",
    price: 134.58,
    change: -3.02,
    marketCap: "$45.1B",
    volume: "6.3M",
    pe: 0,
    eps: -2.05,
    dividend: "0.00%",
    high52: 237.72,
    low52: 122.60,
    day: -3.02,
    week: -6.8,
    month: -4.7,
    year: -24.1,
    aiScore: 5.5,
    confidence: 72,
    risk: "Elevated",
    recommendation: "Hold",
    revenueGrowth: 28,
    earningsGrowth: -8,
    margin: -22,
    debt: "Low",
    sentiment: "Mixed",
    insider: "Neutral",
    valuation: "Needs reacceleration",
    outlook: "Data cloud opportunity is large, but consumption growth needs to stabilize.",
    strengths: ["Data platform scale", "Large cash position", "Enterprise customers"],
    weaknesses: ["Profitability gap", "Growth deceleration", "Competitive pressure"],
    chart: [188, 176, 162, 151, 139, 128, 133, 142, 138, 135]
  },
  {
    ticker: "UBER",
    name: "Uber Technologies",
    logo: "UB",
    sector: "Technology",
    industry: "Software Application",
    country: "United States",
    price: 71.39,
    change: 2.67,
    marketCap: "$149.8B",
    volume: "19.7M",
    pe: 34.6,
    eps: 2.06,
    dividend: "0.00%",
    high52: 82.14,
    low52: 40.09,
    day: 2.67,
    week: 5.4,
    month: 10.2,
    year: 58.1,
    aiScore: 8.0,
    confidence: 86,
    risk: "Medium",
    recommendation: "Buy",
    revenueGrowth: 17,
    earningsGrowth: 62,
    margin: 9,
    debt: "Manageable",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "Fair for margin expansion",
    outlook: "Mobility, delivery, and ads are turning scale into durable free cash flow.",
    strengths: ["Network effects", "Free cash flow inflection", "Delivery scale"],
    weaknesses: ["Regulatory labor risk", "Competition", "Autonomous vehicle risk"],
    chart: [44, 50, 56, 61, 65, 69, 73, 76, 70, 71]
  },
  {
    ticker: "COIN",
    name: "Coinbase",
    logo: "CO",
    sector: "Financial Services",
    industry: "Capital Markets",
    country: "United States",
    price: 236.74,
    change: 6.28,
    marketCap: "$58.2B",
    volume: "12.4M",
    pe: 41.9,
    eps: 5.65,
    dividend: "0.00%",
    high52: 283.48,
    low52: 70.42,
    day: 6.28,
    week: 11.6,
    month: 21.4,
    year: 198.3,
    aiScore: 6.8,
    confidence: 76,
    risk: "Elevated",
    recommendation: "Hold",
    revenueGrowth: 38,
    earningsGrowth: 110,
    margin: 18,
    debt: "Manageable",
    sentiment: "Bullish",
    insider: "Light selling",
    valuation: "Crypto cycle premium",
    outlook: "Trading volume and custody growth rise with crypto markets, but volatility is high.",
    strengths: ["Crypto exchange brand", "Custody growth", "Balance sheet cash"],
    weaknesses: ["Crypto cycle exposure", "Regulatory risk", "Revenue volatility"],
    chart: [82, 103, 126, 148, 174, 202, 219, 251, 229, 237]
  },
  {
    ticker: "RIVN",
    name: "Rivian",
    logo: "RI",
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    country: "United States",
    price: 12.84,
    change: -4.92,
    marketCap: "$12.7B",
    volume: "38.2M",
    pe: 0,
    eps: -4.71,
    dividend: "0.00%",
    high52: 28.06,
    low52: 8.26,
    day: -4.92,
    week: -8.7,
    month: 6.1,
    year: -40.2,
    aiScore: 4.2,
    confidence: 67,
    risk: "Elevated",
    recommendation: "Avoid",
    revenueGrowth: 22,
    earningsGrowth: -12,
    margin: -87,
    debt: "Moderate",
    sentiment: "Bearish",
    insider: "Neutral",
    valuation: "Speculative EV turnaround",
    outlook: "Brand appeal is real, but cash burn and production scale are major hurdles.",
    strengths: ["Strong product reviews", "Amazon relationship", "EV brand recognition"],
    weaknesses: ["Cash burn", "Negative margins", "Competitive EV market"],
    chart: [24, 21, 18, 15, 11, 9, 10, 13, 14, 13]
  },
  {
    ticker: "BABA",
    name: "Alibaba",
    logo: "BA",
    sector: "Consumer Cyclical",
    industry: "Internet Retail",
    country: "China",
    price: 76.18,
    change: 1.76,
    marketCap: "$183.4B",
    volume: "20.8M",
    pe: 10.8,
    eps: 7.05,
    dividend: "1.30%",
    high52: 102.50,
    low52: 66.63,
    day: 1.76,
    week: 3.8,
    month: 7.2,
    year: -7.4,
    aiScore: 6.0,
    confidence: 74,
    risk: "Elevated",
    recommendation: "Hold",
    revenueGrowth: 6,
    earningsGrowth: 8,
    margin: 14,
    debt: "Low",
    sentiment: "Mixed",
    insider: "Neutral",
    valuation: "Cheap with country risk",
    outlook: "Valuation is low, but China macro and competition limit confidence.",
    strengths: ["E-commerce scale", "Cloud asset", "Cheap valuation"],
    weaknesses: ["China policy risk", "Competition", "Slower growth"],
    chart: [91, 86, 80, 73, 68, 70, 74, 78, 75, 76]
  },
  {
    ticker: "TSM",
    name: "Taiwan Semiconductor",
    logo: "TS",
    sector: "Technology",
    industry: "Semiconductors",
    country: "Taiwan",
    price: 171.52,
    change: 2.93,
    marketCap: "$889.2B",
    volume: "14.6M",
    pe: 28.9,
    eps: 5.94,
    dividend: "1.31%",
    high52: 193.47,
    low52: 84.95,
    day: 2.93,
    week: 5.8,
    month: 13.6,
    year: 82.5,
    aiScore: 8.7,
    confidence: 90,
    risk: "Medium",
    recommendation: "Buy",
    revenueGrowth: 30,
    earningsGrowth: 36,
    margin: 42,
    debt: "Low",
    sentiment: "Very bullish",
    insider: "Neutral",
    valuation: "AI foundry premium",
    outlook: "Advanced-node leadership makes TSMC central to AI and high-performance computing.",
    strengths: ["Foundry leadership", "AI demand", "High margins"],
    weaknesses: ["Geopolitical risk", "Capex intensity", "Customer concentration"],
    chart: [92, 104, 118, 132, 146, 155, 164, 176, 168, 172]
  },
  {
    ticker: "ASML",
    name: "ASML Holding",
    logo: "AS",
    sector: "Technology",
    industry: "Semiconductor Equipment",
    country: "Netherlands",
    price: 986.40,
    change: 1.58,
    marketCap: "$389.6B",
    volume: "1.2M",
    pe: 43.7,
    eps: 22.57,
    dividend: "0.79%",
    high52: 1110.09,
    low52: 564.00,
    day: 1.58,
    week: 3.9,
    month: 8.2,
    year: 43.6,
    aiScore: 8.4,
    confidence: 88,
    risk: "Medium",
    recommendation: "Buy",
    revenueGrowth: 15,
    earningsGrowth: 18,
    margin: 28,
    debt: "Low",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "Premium monopoly asset",
    outlook: "EUV lithography remains essential for advanced semiconductor manufacturing.",
    strengths: ["EUV monopoly", "Long-term backlog", "Pricing power"],
    weaknesses: ["Export controls", "Cyclical orders", "High valuation"],
    chart: [642, 701, 754, 812, 869, 923, 971, 1018, 992, 986]
  },
  {
    ticker: "NVO",
    name: "Novo Nordisk",
    logo: "NV",
    sector: "Healthcare",
    industry: "Biotechnology",
    country: "Denmark",
    price: 139.82,
    change: 1.41,
    marketCap: "$624.7B",
    volume: "5.8M",
    pe: 45.2,
    eps: 3.09,
    dividend: "0.95%",
    high52: 148.15,
    low52: 75.56,
    day: 1.41,
    week: 4.6,
    month: 10.4,
    year: 76.2,
    aiScore: 8.8,
    confidence: 91,
    risk: "Medium",
    recommendation: "Strong Buy",
    revenueGrowth: 31,
    earningsGrowth: 38,
    margin: 36,
    debt: "Low",
    sentiment: "Very bullish",
    insider: "Neutral",
    valuation: "Premium GLP-1 leader",
    outlook: "Diabetes and obesity demand create rare multi-year earnings visibility.",
    strengths: ["Obesity leadership", "Global scale", "High margins"],
    weaknesses: ["Manufacturing constraints", "Competition", "Premium valuation"],
    chart: [78, 88, 96, 108, 119, 127, 134, 142, 138, 140]
  },
  {
    ticker: "TM",
    name: "Toyota",
    logo: "TO",
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    country: "Japan",
    price: 204.15,
    change: 0.83,
    marketCap: "$276.8B",
    volume: "0.8M",
    pe: 10.2,
    eps: 20.01,
    dividend: "2.36%",
    high52: 255.23,
    low52: 158.32,
    day: 0.83,
    week: 2.0,
    month: -1.5,
    year: 25.1,
    aiScore: 7.1,
    confidence: 81,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 9,
    earningsGrowth: 18,
    margin: 10,
    debt: "Auto finance leverage",
    sentiment: "Constructive",
    insider: "Neutral",
    valuation: "Reasonable global auto leader",
    outlook: "Hybrid leadership and scale support earnings despite EV uncertainty.",
    strengths: ["Hybrid leadership", "Manufacturing scale", "Brand trust"],
    weaknesses: ["FX exposure", "EV transition risk", "Auto cyclicality"],
    chart: [165, 176, 189, 204, 221, 238, 231, 217, 209, 204]
  },
  {
    ticker: "SPY",
    name: "SPDR S&P 500 ETF",
    logo: "SP",
    sector: "ETF",
    industry: "Large Blend",
    country: "United States",
    price: 546.12,
    change: 0.74,
    marketCap: "$540.0B",
    volume: "58.2M",
    pe: 24.1,
    eps: 22.66,
    dividend: "1.28%",
    high52: 548.53,
    low52: 409.21,
    day: 0.74,
    week: 1.8,
    month: 4.3,
    year: 24.4,
    aiScore: 7.5,
    confidence: 88,
    risk: "Low",
    recommendation: "Hold",
    revenueGrowth: 8,
    earningsGrowth: 10,
    margin: 16,
    debt: "Index weighted",
    sentiment: "Constructive",
    insider: "Neutral",
    valuation: "Broad market benchmark",
    outlook: "A balanced proxy for the S&P 500, useful as a portfolio benchmark.",
    strengths: ["Diversification", "Liquidity", "Benchmark exposure"],
    weaknesses: ["Mega-cap concentration", "Market drawdown risk", "No stock selection edge"],
    chart: [425, 446, 463, 481, 497, 512, 528, 539, 543, 546]
  }
];

export const trendingSearches = ["AI chips", "Mega-cap tech", "Dividend compounders", "Semiconductors", "GLP-1 leaders", "Banks", "Energy", "International stocks"];
export const recentSearches = ["AAPL", "NVDA", "TSLA", "JPM", "GOOGL", "AMZN"];
export const marketNews = [
  "AI infrastructure spending keeps semiconductor leaders near the top of institutional screens.",
  "Healthcare momentum broadens as obesity drug demand reshapes long-term earnings forecasts.",
  "Banks hold gains after stronger capital return plans and resilient consumer credit trends."
];
