export type Recommendation = "Strong Buy" | "Buy" | "Hold" | "Avoid";

export type Stock = {
  ticker: string;
  name: string;
  logo: string;
  sector: string;
  industry: string;
  country: string;
  price: number;
  change: number;
  marketCap: string;
  volume: string;
  pe: number;
  eps: number;
  dividend: string;
  high52: number;
  low52: number;
  day: number;
  week: number;
  month: number;
  year: number;
  aiScore: number;
  confidence: number;
  risk: "Low" | "Medium" | "Elevated";
  recommendation: Recommendation;
  revenueGrowth: number;
  earningsGrowth: number;
  margin: number;
  debt: string;
  sentiment: string;
  insider: string;
  valuation: string;
  outlook: string;
  strengths: string[];
  weaknesses: string[];
  chart: number[];
};

export const stocks: Stock[] = [
  {
    ticker: "NVDA",
    name: "Nvidia",
    logo: "NV",
    sector: "Technology",
    industry: "Semiconductors",
    country: "United States",
    price: 132.48,
    change: 3.42,
    marketCap: "$3.26T",
    volume: "214.8M",
    pe: 49.8,
    eps: 2.71,
    dividend: "0.03%",
    high52: 140.76,
    low52: 85.19,
    day: 3.42,
    week: 6.8,
    month: 11.2,
    year: 74.1,
    aiScore: 9.4,
    confidence: 94,
    risk: "Medium",
    recommendation: "Strong Buy",
    revenueGrowth: 79,
    earningsGrowth: 102,
    margin: 57,
    debt: "Low",
    sentiment: "Very bullish",
    insider: "Neutral",
    valuation: "Premium justified by growth",
    outlook: "AI infrastructure demand remains strong across cloud and enterprise buyers.",
    strengths: ["Dominant AI accelerator position", "Exceptional gross margins", "High free cash flow conversion"],
    weaknesses: ["Premium valuation", "Supply-chain concentration", "Cyclical semiconductor exposure"],
    chart: [108, 112, 110, 116, 121, 119, 125, 127, 126, 132]
  },
  {
    ticker: "AAPL",
    name: "Apple",
    logo: "AP",
    sector: "Technology",
    industry: "Consumer Electronics",
    country: "United States",
    price: 214.29,
    change: 1.18,
    marketCap: "$3.18T",
    volume: "61.2M",
    pe: 32.7,
    eps: 6.57,
    dividend: "0.46%",
    high52: 237.49,
    low52: 164.08,
    day: 1.18,
    week: 2.7,
    month: 5.6,
    year: 11.9,
    aiScore: 8.9,
    confidence: 92,
    risk: "Low",
    recommendation: "Strong Buy",
    revenueGrowth: 6,
    earningsGrowth: 10,
    margin: 46,
    debt: "Manageable",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "Fair for quality",
    outlook: "Services growth and device refresh cycles support resilient cash generation.",
    strengths: ["Massive installed base", "High-margin services", "Shareholder returns"],
    weaknesses: ["Hardware replacement cycles", "Regulatory scrutiny", "China demand sensitivity"],
    chart: [186, 191, 188, 193, 199, 202, 198, 207, 211, 214]
  },
  {
    ticker: "MSFT",
    name: "Microsoft",
    logo: "MS",
    sector: "Technology",
    industry: "Software Infrastructure",
    country: "United States",
    price: 468.72,
    change: 0.84,
    marketCap: "$3.48T",
    volume: "28.4M",
    pe: 36.4,
    eps: 12.88,
    dividend: "0.66%",
    high52: 488.92,
    low52: 362.90,
    day: 0.84,
    week: 3.1,
    month: 7.8,
    year: 28.4,
    aiScore: 9.1,
    confidence: 93,
    risk: "Low",
    recommendation: "Strong Buy",
    revenueGrowth: 16,
    earningsGrowth: 20,
    margin: 44,
    debt: "Low",
    sentiment: "Very bullish",
    insider: "Neutral",
    valuation: "Premium quality compounder",
    outlook: "Cloud, AI copilots, and enterprise subscriptions reinforce durable growth.",
    strengths: ["Azure growth", "Recurring enterprise revenue", "Broad AI distribution"],
    weaknesses: ["High expectations", "Cloud capex intensity", "Regulatory complexity"],
    chart: [401, 416, 421, 419, 432, 444, 451, 459, 462, 469]
  },
  {
    ticker: "TSLA",
    name: "Tesla",
    logo: "TS",
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    country: "United States",
    price: 184.06,
    change: -2.72,
    marketCap: "$586.4B",
    volume: "118.9M",
    pe: 48.1,
    eps: 3.83,
    dividend: "0.00%",
    high52: 299.29,
    low52: 138.80,
    day: -2.72,
    week: -4.5,
    month: 8.4,
    year: -24.8,
    aiScore: 6.4,
    confidence: 78,
    risk: "Elevated",
    recommendation: "Hold",
    revenueGrowth: 4,
    earningsGrowth: -18,
    margin: 18,
    debt: "Low",
    sentiment: "Mixed",
    insider: "Light selling",
    valuation: "Future-growth dependent",
    outlook: "Robotaxi and energy optionality compete with margin pressure in autos.",
    strengths: ["Brand and scale", "Energy storage growth", "Balance sheet flexibility"],
    weaknesses: ["Automotive margin compression", "Demand volatility", "Execution risk"],
    chart: [206, 198, 190, 177, 181, 174, 188, 193, 189, 184]
  },
  {
    ticker: "LLY",
    name: "Eli Lilly",
    logo: "LL",
    sector: "Healthcare",
    industry: "Drug Manufacturers",
    country: "United States",
    price: 884.35,
    change: 2.21,
    marketCap: "$839.1B",
    volume: "3.8M",
    pe: 72.5,
    eps: 12.20,
    dividend: "0.59%",
    high52: 966.10,
    low52: 562.12,
    day: 2.21,
    week: 5.1,
    month: 9.7,
    year: 52.4,
    aiScore: 8.7,
    confidence: 90,
    risk: "Medium",
    recommendation: "Buy",
    revenueGrowth: 27,
    earningsGrowth: 35,
    margin: 39,
    debt: "Moderate",
    sentiment: "Bullish",
    insider: "Neutral",
    valuation: "Premium pipeline valuation",
    outlook: "Obesity and diabetes franchises provide multi-year growth visibility.",
    strengths: ["GLP-1 leadership", "Pricing power", "Pipeline depth"],
    weaknesses: ["Manufacturing constraints", "Patent-cycle exposure", "High valuation"],
    chart: [704, 731, 760, 748, 789, 812, 835, 858, 871, 884]
  },
  {
    ticker: "JPM",
    name: "JPMorgan Chase",
    logo: "JP",
    sector: "Financial Services",
    industry: "Banks",
    country: "United States",
    price: 221.37,
    change: 0.42,
    marketCap: "$621.7B",
    volume: "9.4M",
    pe: 12.4,
    eps: 17.85,
    dividend: "2.08%",
    high52: 230.12,
    low52: 168.44,
    day: 0.42,
    week: 1.6,
    month: 3.2,
    year: 18.9,
    aiScore: 7.8,
    confidence: 86,
    risk: "Low",
    recommendation: "Hold",
    revenueGrowth: 9,
    earningsGrowth: 12,
    margin: 31,
    debt: "Bank leverage",
    sentiment: "Constructive",
    insider: "Neutral",
    valuation: "Attractive versus quality",
    outlook: "Scale advantages and credit discipline support above-peer profitability.",
    strengths: ["Best-in-class balance sheet", "Diversified revenue", "Capital returns"],
    weaknesses: ["Rate sensitivity", "Credit-cycle risk", "Regulatory capital pressure"],
    chart: [188, 193, 197, 202, 199, 207, 214, 218, 216, 221]
  },
  {
    ticker: "XOM",
    name: "Exxon Mobil",
    logo: "XO",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    country: "United States",
    price: 113.64,
    change: -0.68,
    marketCap: "$503.2B",
    volume: "17.1M",
    pe: 13.8,
    eps: 8.23,
    dividend: "3.34%",
    high52: 125.19,
    low52: 95.77,
    day: -0.68,
    week: -1.8,
    month: 2.4,
    year: 6.3,
    aiScore: 6.9,
    confidence: 81,
    risk: "Medium",
    recommendation: "Hold",
    revenueGrowth: 3,
    earningsGrowth: -4,
    margin: 13,
    debt: "Low",
    sentiment: "Neutral",
    insider: "Neutral",
    valuation: "Reasonable",
    outlook: "Cash returns remain attractive while commodity prices drive near-term variance.",
    strengths: ["Low-cost assets", "Dividend durability", "Strong balance sheet"],
    weaknesses: ["Commodity cyclicality", "Energy transition risk", "Lower growth profile"],
    chart: [109, 111, 116, 114, 118, 112, 110, 116, 114, 113]
  },
  {
    ticker: "SHOP",
    name: "Shopify",
    logo: "SH",
    sector: "Technology",
    industry: "Software Application",
    country: "Canada",
    price: 67.82,
    change: -4.14,
    marketCap: "$87.5B",
    volume: "15.6M",
    pe: 61.2,
    eps: 1.11,
    dividend: "0.00%",
    high52: 91.57,
    low52: 48.56,
    day: -4.14,
    week: -6.2,
    month: -3.8,
    year: 8.1,
    aiScore: 5.7,
    confidence: 73,
    risk: "Elevated",
    recommendation: "Hold",
    revenueGrowth: 23,
    earningsGrowth: 15,
    margin: 12,
    debt: "Low",
    sentiment: "Mixed",
    insider: "Neutral",
    valuation: "Growth premium",
    outlook: "Merchant growth is solid, but valuation needs sustained margin expansion.",
    strengths: ["Large merchant ecosystem", "Payments attach rate", "International runway"],
    weaknesses: ["Competitive commerce market", "Premium multiple", "Marketing spend intensity"],
    chart: [75, 78, 72, 70, 68, 71, 69, 73, 70, 68]
  }
];

export const trendingSearches = ["AI chips", "Mega-cap tech", "Dividend compounders", "Cybersecurity", "GLP-1 leaders"];
export const recentSearches = ["AAPL", "NVDA", "TSLA", "JPM"];
export const marketNews = [
  "AI infrastructure spending keeps semiconductor leaders near the top of institutional screens.",
  "Healthcare momentum broadens as obesity drug demand reshapes long-term earnings forecasts.",
  "Banks hold gains after stronger capital return plans and resilient consumer credit trends."
];
